Repository AI-Tutor-2024/Web-v3.0, pull requests merged in 2025-07, with the labels that each got.

#82 [FIX] QA 이슈 해결
  src/app/(routes)/notes/[folderId]/[noteId]/summary/page.tsx
  src/app/components/organisms/NoteList.tsx
Labels: 💎 Feature, 🔨 Refactor

#84 <Refactor> 대면 회의 안건 리팩토링 : 기능 이슈 해결 + 성능 개선 (중복 API 호출 해결)Refactor/iss18
  public/IMG/slide7.png
  src/app/(routes)/home/page.tsx
  src/app/(routes)/notes/[folderId]/[noteId]/confirm/page.tsx
  src/app/(routes)/notes/[folderId]/[noteId]/create-practice/page.tsx
  src/app/(routes)/notes/[folderId]/[noteId]/result/page.tsx
  src/app/(routes)/notes/[folderId]/[noteId]/summary/page.tsx
  src/app/(routes)/notes/[folderId]/page.tsx
  src/app/(routes)/test/page.tsx
  src/app/api/practice/fetchPractice.ts
  src/app/api/practice/savePracticeQuestions.ts
  src/app/api/summaries/fetchSummary.ts
  src/app/api/summaries/index.ts
  src/app/components/atoms/FileUpload.tsx
  src/app/components/molecules/OnBoardingCarousel.tsx
  src/app/components/organisms/NewNoteForm.tsx
  src/app/components/organisms/ReviewQuestions.tsx
  src/app/components/utils/Sidebar.tsx
  src/app/constants/OnBoardingModalImageList.ts
  src/app/utils/api.ts
Labels: 🔨 Refactor

#86 [FEAT] QA리팩토링
  src/app/(routes)/notes/[folderId]/[noteId]/confirm/page.tsx
  src/app/(routes)/notes/[folderId]/[noteId]/create-practice/page.tsx
  src/app/(routes)/notes/[folderId]/[noteId]/result/page.tsx
  src/app/(routes)/notes/[folderId]/[noteId]/summary/page.tsx
  src/app/api/practice/getPractice.ts
  src/app/components/organisms/ReviewQuestions.tsx
Labels: 💎 Feature
